### ISSUE TITLE
Stuff todo before ANN

### ISSUE THREAD

**Issue by tlienart** [tlienart/JuDoc.jl#133]
* [x] register
* [x] update readme (--> bare minimum shift things to docs), 
* [x] add doc badge link to readme
* [x] make sure docs says that it's still alpha but comments are very welcome to make this better
* [x] add a `why` section to home in docs
* [x] include #86 points
* [x] include link to katex stuff: https://utensil-site.github.io/available-in-katex/ 
* [x] #128 
* [x] info for highlight sheet
* [x] tag a patch release in both JuDoc and JuDocTemplates

**Comment by tlienart** [comment]
@JuliaRegistrator register()

**Comment by tlienart** [comment]
@JuliaRegistrator register()

**Comment by tlienart** [comment]
@JuliaRegistrator register()

**Comment by tlienart** [comment]
Patch release with compat caps, and more docs: @JuliaRegistrator register()

**Comment by tlienart** [comment]
small fix @JuliaRegistrator register()
