### ISSUE TITLE
[v0.2] list

### ISSUE THREAD

**Issue by tlienart** [tlienart/JuDoc.jl#144]
0.2 is bound to be a bunch of small improvements including bug fixes since 0.1, docs improvements and some tidying up in the html templating syntax. 
For new features, consider #147 😄 

### Todo

**docs**

* [x] #167 installation instruction specifying python/node (--> revisit and ad comment)
* [x] #169 instructions for project site + add information about paths (everything should start with `/` the root)
* [x] #171 docs for label outside maths mode
* [x] docs for `\file` and `\fig` (context #172)

**others**

* [x] #157 (label outside of math)
* [x] #152 (eval // see PR #156) 
* [x] #155 error if serve is used without a src/ folder around
* [x] #172 fig, link commands
* [x] #160 (ENV ala pycall for node and python3)
* [x] #162 path specification if doing a project site instead of a user site.
* [x] add a NEWS section listing what's happened // maybe mention it on slack + add on readme that can live-eval (#156)

### Done

**docs**

* [x] #131 (docs for code design)
* [x] #153 (clarify assets folder)
* [x] #136 (how to add new template)
* [x] #135 (template demo) 
* [x] #160 (python call was problematic on windows + other windows problems for optimize)

**fixes**

* [x] fix of #142 checking for `DS_Store` everywhere
* [x] #130 (section headers into links)
* [x] #163 via #165 (insertion inside italic/bold env)

#### minor bug fixes

* v0.1.3 fix a problem with parsing of nested code block within an escape block (#151) and a problem with the path to assets (#150)
* v0.1.2 fix a problem with the use of `@async` which would cause hyperreferences to be treated incorrectly
* v0.1.1 project toml fixes

#### JuDocTemplates

* added Hyde
* added Lanyon
* bumped up KaTeX version to 0.10.2

## Bumped to 0.3

* #100 (footnotes) 
* #127 (optional css inlining)
* #161 (RSS feed)
* #134 (table of contents; ~~requires #130 first~~)
* #113 (html templating)
* #132 (html templating)

**Comment by tlienart** [comment]
@JuliaRegistrator register()

**Comment by tlienart** [comment]
@JuliaRegistrator register()

**Comment by tlienart** [comment]
@JuliaRegistrator register() -- compat fix with JuDocTemplates, using lower-bound only.

**Comment by tlienart** [comment]
@JuliaRegistrator register()
