### ISSUE TITLE
[v0.4+] list

### ISSUE THREAD

**Issue by tlienart** [tlienart/JuDoc.jl#216]
#### misc

* [x] JuDoc site along the lines of https://www.getzola.org in JuDoc --> **ongoing work** at https://github.com/tlienart/JuDocWeb
* [x] use validator (https://validator.w3.org/) on pages to see whether anything odd (like unbalanced ps)

#### features

* [x] check that `` `[link]` `` with `` [link]: ... `` is ok but not `` [`link`] `` ? (test)
* [x] add a local page var which gets all the code of the page? (can be used in tutorials for "just give me the code" step)
* [x] with `serve` announce clearly the activation of the environment, and maybe don't deactivate by default, maybe just say after CTRL+C that can reactivate general env.
* [x] the  return of NodeJS for power user and docker see #294 with a simple solution

#### docs

* [x] update docs of `Node`, should now work thanks to `NodeJS.jl`
* [x] doc of `jd2html` function
* [x] doc of workflow for RSS
* [x] doc of kwargs for serve for instance `reeval`
* [x] doc of approach to get the Project.toml
* [x] doc of additional local and global page vars
* [x] check that docs for `{{ispage ...}}` are correct should be `{{ispage index.html}}` and not `{{ispage /index.html}}`
* [x] docs of new things for code eval, `jd_code` variable, `reeval`, `freezecode` and generally of eval workflow
* [x] docs for literate integration + example in JuDocTemplates
* [x] docs/example for the "use Julia to generate JuDoc" (see #251 )
* [x] docs for `\show`
* [x] docs for `mintoclevel` and `maxtoclevel` (indicate that website-wide settings for the moment)
* [x] docs for `verify_links`
* [x] docs for indented code blocks not within other code blocks
* [x] joker for ispage

#### other 

* [ ] discourse annoucement 😄 for what's happened since 0.1

### Done 🎉 

(not going to release a minor version until I've spent some time on the docs)

####

* [x] allow passing of final hook function which can be used to  work with the  `lunr` search library (PR #320 issue #319) 
* [x] fix an issue with auto-title when no title is provided  the first header is used (PR ~~#317~~ #318)
* [x] fix an issue when using code in a link reference like ``[`A`]: http://example.com`` issue #314 PR #315.
* [x] improvements to the markdown parser bringing marginal speed gains and robustness #312
* [x] allow disabling of support for indented code blocks and better error context #311 

#### to 0.3.10 (tagged 🎉 , did something  stupid with 0.3.9)

* [x] replaced a shell `chmod` with Julia's chmod (issue #305, fixed with https://github.com/tlienart/JuDocTemplates.jl/pull/26) + bumped up the compat bound with judoctemplates
* [x] added Joker support for ispage #304 
* [x] added minimal-mistakes theme on JuDocTemplates
* [x] fix issue with all-caps language like `TOML` not being properly recognised

#### to 0.3.8 (tagged 🎉 )

* [x] a number of small changes  to  accomodate some recent Julia novelties (PR #298) 
* [x] improvements of how JuDoc handles indented lines within other blocks (PR #298) to avoid just plain discarding any formatting in  code blocks for instance
* [x] update of NodeJS (PR #297 effectively  done  in  #298)
* [x] allow custom node installation thanks to @trigaut (PR #295) 

#### to 0.3.7 (tagged 🎉 )

* [x] (bug fix) fixed a sneaky bug with OCBlocks finishing at the end of the file and that prevented latex from being used properly with/in/around headers (PR #291)

#### to 0.3.6 (tagged 🎉 )

* [x]  (bug fix) ordering of latex def in config.md issue #289 and PR #290 
* [x] (enhancement) add a `silent` keyword to `serve` to suppress all output PR #290 
* [x] (experimental feature) ignoring indented code blocks within any other blocks #285 and PR #286 
* [x] (experimental feature) internal and external link checker PR #274 
* [x] (bug fix) PR #273 fixes an issue if you had footnote-like symbols in code blocks
* [x] (enhancement) issues #113 and #132 closed by PR #268 allowing nesting of conditional blocks in HTML templating
* [x] (feature) added possibility to start table of content at level 2 or higher via **global page variable** `mintoclevel` (PR #269) also now `maxtoclevel` (PR #275) and PR #276 cleans it up by allowing local page control of levels
* [x] (feature) allow the literate style `#src` to hide a line

#### to 0.3.5 (tagged 🎉 )

* [x] (JuDocTemplates fix) there was still an issue with file permissions and `newsite` reported https://github.com/tlienart/JuDocTemplates.jl/issues/22 and fixed by adding an explicit `chmod 644` step in the `newsite` function see [these lines](https://github.com/tlienart/JuDocTemplates.jl/blob/9e8757e9842aca4465bfce487c1e5553f987d58d/src/JuDocTemplates.jl#L49-L53)
* [x] (bug fix and improvements) PR #255, #253, and #252, and #267 fix a few issues with resolving link references that were caused by the new RSS features, and the workflow for code evaluation (and avoiding code evals if not necessary) is improved, addition of a few local page vars to manage code evaluation.
* [x] (feature) added experimental support for tight integration with literate PR #257, PR #264 
* [x] (feature) added a `\show` for cell result PR #258 
* [x] (bug fix) in the optimization pass trailing unicode characters could cause failure due to bad string indexing, PR #260 
* [x] (enhancement) use NodeJS to reduce potential issues with node installations issue #262, PR #263 

#### to 0.3.4 (tagged 🎉 )

* [x] (internal) PR #249 replaces usage of most plain `Dict` by `LittleDict`
* [x] (bug fix) PR #249 properly checks whether a code block has already been evaluated to avoid multiple evaluation of the same code blocks on a page; it also adds a possibility to force the re-evaluation of all code blocks (`reeval` kwarg in `serve`)
* [x] (bug fix) PR #248 closes #241, now headers that appear more than once are numbered after a double underscore `example__2` so that they cannot clash with the reference to a header of name `example 2`; also `refstring` changes to replace double underscores that may be present in the title by a single one.  (thanks to @TotalVerb for the idea); also cleaned up the implementation using an ordered dict.
* [x] (feature) PR #242 added **experimental** support for RSS feed generation (closes FR #161)
* [x] (bug fix) PR #237 fixes an issue with automatic table of contents when the level of nesting jumps by more than one (thanks to @TotalVerb)
* [x] (bug fix) PR #238 fixes an issue with automatic header reference numbering which wasn't incrementing (thanks to @TotalVerb) 
* [x] (bug fix) PR #239 fixes an issue with ASCII symbols close to dollar signs, also compatibility requirement raised to Julia 1.1 now otherwise pre-rendering fails (thanks to @TotalVerb) 

#### to 0.3.3 (tagged 🎉 )

* [x] (feature) #145 add command to quickly display the html corresponding to one pass (basically export seval, doc that has limitations of jdvars) PR #235 
* [x] (bug fixes) #222, #223, #234 PR #235 
* [x] (feature) support for penta ticks #219  PR #235 

#### to 0.3.2 (tagged 🎉 )

* [x] (feature) #100 (footnotes support and improved link resolution) see pr #230 
* [x] (bug fix) fixed an issue with indirect links that have special characters in them like ``[`blah`][]`` pr #231 
* (templates) update of [JuDocTemplates](https://github.com/tlienart/JuDocTemplates.jl) to use and showcase the new stuff in 0.3.1 and 0.3.2 ([in action](https://tlienart.github.io/JuDocTemplates.jl/)), tagging of 0.2.6

#### to 0.3.1 (tagged 🎉 )

* [x] (bug fix) fix header links and toc, see #224 
* [x] (bug fix) fix an issue with tables not parsing properly if present immediately after a header, PR #225 
* [x] (bug fix) fix an issue with plain code blocks not being recognised as default language and including spurious top and bottom empty lines PR #226 
* [x] (bug fix) fix a conflict of globally defined variable vs locally defined oness PR #227  
* [x] (feature) added a few options to optimize to allow passing over things that don't prerender well (very rare) and suppress error messages #228
